sql:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost/importdb?sslmode=disable

log:
  level: info
  output: logs/app_log-%Y-%m-%d.log
  map:
    time: "@timestamp"
    msg: message