sql:
  driver: mysql
  data_source_name: root:abcd1234@/masterdata?charset=utf8&parseTime=True&loc=Local

log:
  level: info
  output: logs/app_log-%Y-%m-%d.log
  map:
    time: "@timestamp"
    msg: message